version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_DB:-block-indexer}' 
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME:-admin}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD:-password}'
      MONGO_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init-mongo.sh
    volumes:
      - ./mongodb:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    

  web-app:
    build: ./webApp/
    container_name: webApp
    restart: always
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-block-indexer}
      PORT: ${WEB_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo

  block-indexer:
    build: ./block-indexer/
    container_name: blockIndexer
    restart: always
    ports:
      - '8080:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-block-indexer}
      PORT: ${BLOCK_INDEXER_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      QUEUE_NAME: block-indexer-queue
      INFURA_PROJECT_ID: d7867e69855b48a48f3c4c8d712e0c13
      NETWORK_NAME: goerli
      RABBIT_MQ_URL: admin:admin1234@rabbitmq:5672
      BLOCK_INDEXER_QUEUE: block-indexer-queue
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./lib-indexer:/lib-indexer

  address-indexer:
    build: ./addressIndexer/
    container_name: AddressIndexer
    restart: always
    ports:
      - '8081:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-block-indexer}
      PORT: ${ADDRESS_INDEXER_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      QUEUE_NAME: address-indexer-queue
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo

  token-indexer:
    build: ./tokenIndexer/
    container_name: TokenIndexer
    restart: always
    ports:
      - '8082:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-block-indexer}
      PORT: ${TOKEN_INDEXER_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      QUEUE_NAME: token-indexer-queue
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo

  transaction-indexer:
    build: ./transactionIndexer/
    container_name: TransactionIndexer
    restart: always
    ports:
      - '8083:80'
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/}
      MONGO_DB: ${MONGO_DB:-block-indexer}
      PORT: ${TRANSACTION_INDEXER_APP:-80}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      QUEUE_NAME: transaction-indexer-queue
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin1234
    ports:
      - "15672:15672"
      - "5672:5672"